# Generated by Django 5.2.5 on 2025-12-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_create_report_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
