# Generated by Django 5.2.5 on 2025-08-21 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_workflow', models.BooleanField(default=True, help_text='Receive email notifications for workflow events')),
                ('email_machine', models.BooleanField(default=True, help_text='Receive email notifications for machine events')),
                ('email_maintenance', models.BooleanField(default=True, help_text='Receive email notifications for maintenance events')),
                ('email_quality', models.BooleanField(default=True, help_text='Receive email notifications for quality events')),
                ('email_allocation', models.BooleanField(default=True, help_text='Receive email notifications for allocation events')),
                ('email_system', models.BooleanField(default=True, help_text='Receive email notifications for system events')),
                ('app_workflow', models.BooleanField(default=True, help_text='Receive in-app notifications for workflow events')),
                ('app_machine', models.BooleanField(default=True, help_text='Receive in-app notifications for machine events')),
                ('app_maintenance', models.BooleanField(default=True, help_text='Receive in-app notifications for maintenance events')),
                ('app_quality', models.BooleanField(default=True, help_text='Receive in-app notifications for quality events')),
                ('app_allocation', models.BooleanField(default=True, help_text='Receive in-app notifications for allocation events')),
                ('app_system', models.BooleanField(default=True, help_text='Receive in-app notifications for system events')),
                ('digest_frequency', models.CharField(choices=[('none', 'No Digest'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Frequency for notification digest emails', max_length=10)),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start time for quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End time for quiet hours', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the notification', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Notification title/subject', max_length=255)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('type', models.CharField(choices=[('workflow', 'Workflow'), ('machine', 'Machine'), ('maintenance', 'Maintenance'), ('quality', 'Quality'), ('allocation', 'Allocation'), ('system', 'System')], default='system', help_text='Type of notification based on source app', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', help_text='Priority level of the notification', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was marked as read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('related_object_type', models.CharField(blank=True, help_text="Type of related object (e.g., 'batch', 'machine', 'maintenance_log')", max_length=50, null=True)),
                ('related_object_id', models.UUIDField(blank=True, help_text='ID of the related object', null=True)),
                ('recipient', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, help_text='User who sent this notification (for admin-sent notifications)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['type', '-created_at'], name='notificatio_type_36f2e6_idx'), models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_3fc670_idx')],
            },
        ),
    ]
