# Generated by Django 5.2.5 on 2025-08-20 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0002_alter_batchworkflow_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_type', models.CharField(choices=[('cotton_fabric', 'Cotton Fabric'), ('cotton_yarn', 'Cotton Yarn'), ('blended_fabric', 'Blended Fabric'), ('dyed_fabric', 'Dyed Fabric'), ('printed_fabric', 'Printed Fabric')], max_length=50, unique=True)),
                ('max_defects_per_batch', models.PositiveIntegerField(default=5, help_text='Maximum allowed defects per batch')),
                ('critical_defect_tolerance', models.PositiveIntegerField(default=0, help_text='Maximum allowed high-severity defects')),
                ('quality_threshold', models.FloatField(default=0.95, help_text='Minimum quality score (0.0 to 1.0)')),
                ('thread_count_min', models.PositiveIntegerField(blank=True, null=True)),
                ('thread_count_max', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_tolerance', models.FloatField(default=0.05, help_text='Weight tolerance as percentage (0.05 = 5%)')),
                ('color_fastness_grade', models.CharField(default='4-5', help_text='Minimum color fastness grade', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quality Standard',
                'verbose_name_plural': 'Quality Standards',
                'ordering': ['product_type'],
            },
        ),
        migrations.CreateModel(
            name='QualityMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date for this metrics snapshot')),
                ('total_checks', models.PositiveIntegerField(default=0)),
                ('defects_found', models.PositiveIntegerField(default=0)),
                ('batches_approved', models.PositiveIntegerField(default=0)),
                ('batches_rejected', models.PositiveIntegerField(default=0)),
                ('overall_quality_score', models.FloatField(default=0.0, help_text='Overall quality score for the day (0.0 to 1.0)')),
                ('defect_rate', models.FloatField(default=0.0, help_text='Percentage of checks with defects found')),
                ('approval_rate', models.FloatField(default=0.0, help_text='Percentage of batches approved')),
                ('ai_accuracy', models.FloatField(blank=True, help_text='AI detection accuracy compared to inspector findings', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quality Metrics',
                'verbose_name_plural': 'Quality Metrics',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Photo of the textile sample for quality inspection', upload_to='quality/')),
                ('defect_detected', models.BooleanField(default=False, help_text='Whether any defects were found in this check')),
                ('defect_type', models.CharField(blank=True, choices=[('stain', 'Stain'), ('tear', 'Tear'), ('weave_error', 'Weave Error'), ('color_variation', 'Color Variation'), ('thread_break', 'Thread Break'), ('contamination', 'Contamination'), ('sizing_issue', 'Sizing Issue'), ('density_variation', 'Density Variation')], help_text='Type of defect if detected', max_length=50, null=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', help_text='Severity level of the defect', max_length=10)),
                ('comments', models.TextField(blank=True, help_text='Additional inspector comments and observations', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the quality check', max_length=10)),
                ('ai_analysis_requested', models.BooleanField(default=True, help_text='Whether AI analysis was requested for this image')),
                ('ai_analysis_result', models.JSONField(blank=True, help_text='AI analysis results stored as JSON', null=True)),
                ('ai_confidence_score', models.FloatField(blank=True, help_text='AI confidence score (0.0 to 1.0)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='Batch being inspected', on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='workflow.batchworkflow')),
                ('inspector', models.ForeignKey(help_text='Inspector who performed the quality check', limit_choices_to={'role': 'inspector'}, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quality Check',
                'verbose_name_plural': 'Quality Checks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', 'status'], name='quality_qua_batch_i_0b881e_idx'), models.Index(fields=['inspector', 'created_at'], name='quality_qua_inspect_c6c007_idx'), models.Index(fields=['defect_detected', 'severity'], name='quality_qua_defect__180244_idx')],
            },
        ),
    ]
