# Generated by Django 5.2.5 on 2025-08-25 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_alter_qualitycheck_inspector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheck',
            name='inspector',
            field=models.ForeignKey(help_text='Inspector who performed the quality check', on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to=settings.AUTH_USER_MODEL),
        ),
    ]
