# Generated by Django 5.2.5 on 2025-08-20 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0002_alter_batchworkflow_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_workforce', models.PositiveIntegerField(default=0, help_text='Total workers allocated')),
                ('total_material_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total material cost in XOF', max_digits=12)),
                ('material_count', models.PositiveIntegerField(default=0, help_text='Number of material types allocated')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(help_text='Production batch', on_delete=django.db.models.deletion.CASCADE, related_name='allocation_summary', to='workflow.batchworkflow')),
            ],
            options={
                'verbose_name': 'Allocation Summary',
                'verbose_name_plural': 'Allocation Summaries',
            },
        ),
        migrations.CreateModel(
            name='MaterialAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_name', models.CharField(help_text='Material name (e.g., cotton yarn, dye)', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Quantity allocated', max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('meters', 'Meters'), ('liters', 'Liters'), ('pieces', 'Pieces'), ('rolls', 'Rolls'), ('tons', 'Tons')], help_text='Unit of measurement', max_length=20)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit in XOF', max_digits=10, null=True)),
                ('supplier', models.CharField(blank=True, help_text='Material supplier', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(help_text='Who made this allocation', limit_choices_to={'role__in': ['supervisor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_allocations_made', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(help_text='Production batch', on_delete=django.db.models.deletion.CASCADE, related_name='material_allocations', to='workflow.batchworkflow')),
            ],
            options={
                'verbose_name': 'Material Allocation',
                'verbose_name_plural': 'Material Allocations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', 'material_name'], name='allocation__batch_i_de0ed4_idx'), models.Index(fields=['material_name', 'unit'], name='allocation__materia_f0aed9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkforceAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_assigned', models.CharField(blank=True, choices=[('operator', 'Operator'), ('maintenance', 'Maintenance'), ('qc', 'Quality Control'), ('supervisor', 'Supervisor'), ('assistant', 'Assistant')], help_text='Role in this batch', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Allocation start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Allocation end date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_by', models.ForeignKey(help_text='Who made this allocation', limit_choices_to={'role__in': ['supervisor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workforce_allocations_made', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(help_text='Production batch', on_delete=django.db.models.deletion.CASCADE, related_name='workforce_allocations', to='workflow.batchworkflow')),
                ('user', models.ForeignKey(help_text='Allocated worker', on_delete=django.db.models.deletion.CASCADE, related_name='workforce_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workforce Allocation',
                'verbose_name_plural': 'Workforce Allocations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', 'user'], name='allocation__batch_i_2b4236_idx'), models.Index(fields=['start_date', 'end_date'], name='allocation__start_d_175959_idx')],
                'unique_together': {('batch', 'user', 'role_assigned')},
            },
        ),
    ]
