# Generated by Django 5.2.5 on 2025-08-20 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the maintenance log', primary_key=True, serialize=False)),
                ('issue_reported', models.TextField(help_text='Description of the issue or maintenance required')),
                ('action_taken', models.TextField(blank=True, help_text='Description of actions taken to resolve the issue', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Current status of the maintenance', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True, help_text='When the maintenance was reported')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the maintenance was resolved', null=True)),
                ('next_due_date', models.DateField(blank=True, help_text='Recommended date for next maintenance', null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the maintenance', max_length=10)),
                ('downtime_hours', models.FloatField(blank=True, help_text='Machine downtime in hours', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of maintenance in CFA francs', max_digits=10, null=True)),
                ('parts_replaced', models.TextField(blank=True, help_text='List of parts that were replaced', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the maintenance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the maintenance log was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the maintenance log was last updated')),
                ('machine', models.ForeignKey(help_text='Machine being maintained', on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_logs', to='machines.machine')),
                ('technician', models.ForeignKey(help_text='Technician assigned to this maintenance', limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Log',
                'verbose_name_plural': 'Maintenance Logs',
                'db_table': 'maintenance_log',
                'ordering': ['-reported_at', '-created_at'],
                'indexes': [models.Index(fields=['machine'], name='maintenance_machine_21c2df_idx'), models.Index(fields=['technician'], name='maintenance_technic_41c0ac_idx'), models.Index(fields=['status'], name='maintenance_status_c80d59_idx'), models.Index(fields=['priority'], name='maintenance_priorit_f8c3bf_idx'), models.Index(fields=['reported_at'], name='maintenance_reporte_a69a95_idx'), models.Index(fields=['next_due_date'], name='maintenance_next_du_ba7c91_idx'), models.Index(fields=['created_at'], name='maintenance_created_560226_idx')],
            },
        ),
    ]
