import apiService from '../src/services/api';
import { Machine, MachineType, PaginatedResponse } from '../src/types/api';

export type { Machine, MachineType } from '../src/types/api';

export interface MachineStats {
  total_machines: number;
  active_machines: number;
  running_machines: number;
  idle_machines: number;
  maintenance_machines: number;
  breakdown_machines: number;
  offline_machines: number;
  by_type: Record<string, number>;
  by_location: Record<string, number>;
  by_operator: Record<string, number>;
  average_operating_hours: number;
  maintenance_due_count: number;
}

export interface MachineListResponse {
  success: boolean;
  message: string;
  data: {
    count: number;
    next: string | null;
    previous: string | null;
    results: Machine[];
  };
}

export interface MachineDetailResponse {
  success: boolean;
  message: string;
  data: Machine;
}

export interface MachineStatsResponse {
  success: boolean;
  message: string;
  data: MachineStats;
}

export interface MachineCreateData {
  machine_id?: string; // Optional - auto-generated by backend
  name: string;
  machine_type: string; // ID of machine type for API
  manufacturer?: string;
  model_number?: string;
  serial_number?: string;
  installation_date?: string;
  building?: string;
  floor?: string;
  location_details?: string;
  operational_status?: 'running' | 'idle' | 'maintenance' | 'breakdown' | 'offline';
  rated_power?: number;
  rated_capacity?: number;
  capacity_unit?: string;
  primary_operator?: string; // User ID
  notes?: string;
  warranty_expiry?: string;
  purchase_cost?: string;
  site_code: string;
}

export interface MachineUpdateData {
  machine_id?: string;
  name?: string;
  machine_type?: string; // ID of machine type for API
  manufacturer?: string;
  model_number?: string;
  serial_number?: string;
  installation_date?: string;
  building?: string;
  floor?: string;
  location_details?: string;
  operational_status?: 'running' | 'idle' | 'maintenance' | 'breakdown' | 'offline';
  rated_power?: number;
  rated_capacity?: number;
  capacity_unit?: string;
  primary_operator?: string;
  notes?: string;
  warranty_expiry?: string;
  purchase_cost?: string;
  status?: 'active' | 'inactive' | 'pending' | 'archived';
  // Allow site_code in updates when the UI provides it (optional)
  site_code?: string;
}

export interface MachineFilters {
  search?: string;
  machine_type?: string;
  operational_status?: string;
  primary_operator?: string;
  building?: string;
  site_code?: string;
  maintenance_due?: boolean;
  created_by_role?: string;
  ordering?: string;
  page?: number;
  page_size?: number;
}

class MachineService {
  async getMachines(filters: MachineFilters = {}): Promise<MachineListResponse> {
    try {
      console.log('MachineService: Calling apiService.getMachines with filters:', filters);
      
      // Use the real API service
      const response = await apiService.getMachines(filters);
      console.log('MachineService: Raw API response received:', response);
      console.log('MachineService: Response type:', typeof response);
      console.log('MachineService: Response keys:', response ? Object.keys(response) : 'No response');
      console.log('MachineService: Full response structure:', JSON.stringify(response, null, 2));
      console.log('MachineService: Results in response:', response?.results);
      console.log('MachineService: Results length:', response?.results?.length);
      console.log('MachineService: Count in response:', response?.count);
      
      return {
        success: true,
        message: 'Machines retrieved successfully',
        data: {
          count: response.count || 0,
          next: response.next || null,
          previous: response.previous || null,
          results: response.results || []
        }
      };
    } catch (error) {
      console.error('MachineService: Error fetching machines:', error);
      
      // Return a failed response instead of throwing
      return {
        success: false,
        message: error instanceof Error ? error.message : 'Failed to fetch machines',
        data: {
          count: 0,
          next: null,
          previous: null,
          results: []
        }
      };
    }
  }

  async getMachineById(id: string): Promise<MachineDetailResponse> {
    try {
      const machine = await apiService.getMachineById(id);
      return {
        success: true,
        message: 'Machine retrieved successfully',
        data: machine
      };
    } catch (error) {
      console.error('Error fetching machine:', error);
      throw error;
    }
  }

  async createMachine(machineData: MachineCreateData): Promise<MachineDetailResponse> {
    try {
      // Convert MachineCreateData to the format expected by the API
      const apiData = {
        ...machineData,
        // The API expects machine_type as a string ID, which is what we already have
      } as any; // Cast to any to avoid type conflicts during creation
      
      const machine = await apiService.createMachine(apiData);
      return {
        success: true,
        message: 'Machine created successfully',
        data: machine
      };
    } catch (error) {
      console.error('Error creating machine:', error);
      throw error;
    }
  }

  async updateMachine(id: string, machineData: MachineUpdateData): Promise<MachineDetailResponse> {
    try {
      // Convert MachineUpdateData to the format expected by the API
      const apiData = {
        ...machineData,
        // The API expects machine_type as a string ID, which is what we already have
      } as any; // Cast to any to avoid type conflicts during update
      
      console.log('Machine service updateMachine called with:', { id, machineData, apiData });
      
      const machine = await apiService.updateMachine(id, apiData);
      return {
        success: true,
        message: 'Machine updated successfully',
        data: machine
      };
    } catch (error: any) {
      console.error('Error updating machine:', error);
      console.error('Error response:', error.response?.data);
      console.error('Error status:', error.response?.status);
      throw error;
    }
  }

  async deleteMachine(id: string): Promise<{ success: boolean; message: string }> {
    try {
      await apiService.deleteMachine(id);
      return {
        success: true,
        message: 'Machine deleted successfully'
      };
    } catch (error) {
      console.error('Error deleting machine:', error);
      throw error;
    }
  }

  async getMachineTypes(): Promise<{ success: boolean; message: string; data: MachineType[] }> {
    try {
      const types = await apiService.getMachineTypes();
      return {
        success: true,
        message: 'Machine types retrieved successfully',
        data: types.results || types
      };
    } catch (error) {
      console.error('Error fetching machine types:', error);
      throw error;
    }
  }

  async getMachineStats(): Promise<MachineStatsResponse> {
    try {
      // Get all machines and calculate stats
      const machines = await this.getMachines();
      const machineList = machines.data?.results || [];
      
      // Safety check for machineList
      if (!Array.isArray(machineList)) {
        console.warn('Machine list is not an array:', machineList);
        return {
          success: true,
          message: 'Machine statistics retrieved successfully (empty)',
          data: {
            total_machines: 0,
            active_machines: 0,
            running_machines: 0,
            idle_machines: 0,
            maintenance_machines: 0,
            breakdown_machines: 0,
            offline_machines: 0,
            by_type: {},
            by_location: {},
            by_operator: {},
            average_operating_hours: 0,
            maintenance_due_count: 0
          }
        };
      }
      
      const stats: MachineStats = {
        total_machines: machineList.length,
        active_machines: machineList.filter(m => m.status === 'active').length,
        running_machines: machineList.filter(m => m.operational_status === 'running').length,
        idle_machines: machineList.filter(m => m.operational_status === 'idle').length,
        maintenance_machines: machineList.filter(m => m.operational_status === 'maintenance').length,
        breakdown_machines: machineList.filter(m => m.operational_status === 'breakdown').length,
        offline_machines: machineList.filter(m => m.operational_status === 'offline').length,
        by_type: machineList.reduce((acc, machine) => {
          const type = typeof machine.machine_type === 'object' 
            ? machine.machine_type?.name || 'Unknown'
            : 'Unknown';
          acc[type] = (acc[type] || 0) + 1;
          return acc;
        }, {} as Record<string, number>),
        by_location: machineList.reduce((acc, machine) => {
          if (machine.building) {
            acc[machine.building] = (acc[machine.building] || 0) + 1;
          }
          return acc;
        }, {} as Record<string, number>),
        by_operator: machineList.reduce((acc, machine) => {
          if (machine.primary_operator) {
            const operatorName = `${machine.primary_operator.first_name} ${machine.primary_operator.last_name}`.trim();
            acc[operatorName] = (acc[operatorName] || 0) + 1;
          }
          return acc;
        }, {} as Record<string, number>),
        average_operating_hours: machineList.length > 0 
          ? machineList.reduce((sum, m) => sum + (m.total_operating_hours || 0), 0) / machineList.length 
          : 0,
        maintenance_due_count: machineList.filter(m => m.needs_maintenance === true).length
      };

      return {
        success: true,
        message: 'Machine statistics retrieved successfully',
        data: stats
      };
    } catch (error) {
      console.error('Error fetching machine stats:', error);
      // Return empty stats on error
      return {
        success: false,
        message: 'Failed to fetch machine statistics',
        data: {
          total_machines: 0,
          active_machines: 0,
          running_machines: 0,
          idle_machines: 0,
          maintenance_machines: 0,
          breakdown_machines: 0,
          offline_machines: 0,
          by_type: {},
          by_location: {},
          by_operator: {},
          average_operating_hours: 0,
          maintenance_due_count: 0
        }
      };
    }
  }

  // Helper methods for display
  getOperationalStatusDisplay(status: string): string {
    const statusMap: Record<string, string> = {
      'running': 'Running',
      'idle': 'Idle',
      'maintenance': 'Under Maintenance',
      'breakdown': 'Breakdown',
      'offline': 'Offline'
    };
    return statusMap[status] || status;
  }

  getOperationalStatusColor(status: string): string {
    const colorMap: Record<string, string> = {
      'running': 'bg-green-100 text-green-800',
      'idle': 'bg-yellow-100 text-yellow-800',
      'maintenance': 'bg-blue-100 text-blue-800',
      'breakdown': 'bg-red-100 text-red-800',
      'offline': 'bg-gray-100 text-gray-800'
    };
    return colorMap[status] || 'bg-gray-100 text-gray-800';
  }

  getMaintenanceUrgencyColor(urgency: string): string {
    const colorMap: Record<string, string> = {
      'normal': 'bg-green-100 text-green-800',
      'due_soon': 'bg-yellow-100 text-yellow-800',
      'urgent': 'bg-orange-100 text-orange-800',
      'critical': 'bg-red-100 text-red-800',
      'unknown': 'bg-gray-100 text-gray-800'
    };
    return colorMap[urgency] || 'bg-gray-100 text-gray-800';
  }

  getStatusDisplayName(status: string): string {
    const statusMap: Record<string, string> = {
      'active': 'Active',
      'inactive': 'Inactive', 
      'pending': 'Pending',
      'archived': 'Archived'
    };
    return statusMap[status] || status;
  }

  getStatusBadgeColor(status: string): string {
    const colorMap: Record<string, string> = {
      'active': 'bg-green-100 text-green-800',
      'inactive': 'bg-gray-100 text-gray-800',
      'pending': 'bg-yellow-100 text-yellow-800',
      'archived': 'bg-red-100 text-red-800'
    };
    return colorMap[status] || 'bg-gray-100 text-gray-800';
  }
}

export const machineService = new MachineService();

// Export individual methods for easier importing
export const getMachines = (filters?: MachineFilters) => machineService.getMachines(filters);
export const getMachineById = (id: string) => machineService.getMachineById(id);
export const createMachine = (data: MachineCreateData) => machineService.createMachine(data);
export const updateMachine = (id: string, data: MachineUpdateData) => machineService.updateMachine(id, data);
export const deleteMachine = (id: string) => machineService.deleteMachine(id);
export const getMachineTypes = () => machineService.getMachineTypes();
export const getMachineStats = () => machineService.getMachineStats();
