# Generated by Django 5.2.5 on 2025-08-20 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Machine type name (e.g., "Cotton Gin", "Spinning Machine")', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of machine type')),
                ('manufacturer', models.CharField(blank=True, help_text='Common manufacturer for this machine type', max_length=100)),
                ('typical_power_consumption', models.FloatField(blank=True, help_text='Typical power consumption in kW', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('typical_production_rate', models.FloatField(blank=True, help_text='Typical production rate per hour', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('production_unit', models.CharField(blank=True, help_text='Unit for production rate (kg/hr, m/hr, etc.)', max_length=20)),
                ('recommended_maintenance_interval_hours', models.PositiveIntegerField(blank=True, help_text='Recommended maintenance interval in operating hours', null=True)),
                ('recommended_maintenance_interval_days', models.PositiveIntegerField(blank=True, help_text='Recommended maintenance interval in calendar days', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Machine Type',
                'verbose_name_plural': 'Machine Types',
                'db_table': 'machines_machinetype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_code', models.CharField(help_text='CMDT site/factory code', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('archived', 'Archived')], default='active', max_length=20)),
                ('machine_id', models.CharField(help_text='Unique machine identifier (e.g., CTN-GIN-001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable machine name', max_length=200)),
                ('manufacturer', models.CharField(blank=True, help_text='Machine manufacturer', max_length=100)),
                ('model_number', models.CharField(blank=True, help_text='Manufacturer model number', max_length=100)),
                ('serial_number', models.CharField(blank=True, help_text='Machine serial number', max_length=100)),
                ('installation_date', models.DateField(blank=True, help_text='Date machine was installed', null=True)),
                ('building', models.CharField(blank=True, help_text='Building or area within site', max_length=100)),
                ('floor', models.CharField(blank=True, help_text='Floor level', max_length=50)),
                ('location_details', models.TextField(blank=True, help_text='Detailed location description')),
                ('operational_status', models.CharField(choices=[('running', 'Running'), ('idle', 'Idle'), ('maintenance', 'Under Maintenance'), ('breakdown', 'Breakdown'), ('offline', 'Offline')], default='offline', help_text='Current operational status', max_length=20)),
                ('total_operating_hours', models.FloatField(default=0, help_text='Total operating hours since installation', validators=[django.core.validators.MinValueValidator(0)])),
                ('hours_since_maintenance', models.FloatField(default=0, help_text='Operating hours since last maintenance', validators=[django.core.validators.MinValueValidator(0)])),
                ('rated_power', models.FloatField(blank=True, help_text='Rated power consumption in kW', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rated_capacity', models.FloatField(blank=True, help_text='Rated production capacity', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity_unit', models.CharField(blank=True, help_text='Unit for capacity (kg/hr, m/hr, etc.)', max_length=20)),
                ('last_maintenance_date', models.DateTimeField(blank=True, help_text='Date of last maintenance', null=True)),
                ('next_maintenance_date', models.DateTimeField(blank=True, help_text='Scheduled date for next maintenance', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the machine')),
                ('warranty_expiry', models.DateField(blank=True, help_text='Warranty expiry date', null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase cost in CFA francs', max_digits=12, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('primary_operator', models.ForeignKey(blank=True, help_text='Primary operator responsible for this machine', limit_choices_to={'role__in': ['technician', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_machines', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='machines.machinetype')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'db_table': 'machines_machine',
                'ordering': ['site_code', 'machine_id'],
                'indexes': [models.Index(fields=['machine_id'], name='machines_ma_machine_2acfe1_idx'), models.Index(fields=['operational_status'], name='machines_ma_operati_c7367c_idx'), models.Index(fields=['machine_type'], name='machines_ma_machine_330f26_idx'), models.Index(fields=['primary_operator'], name='machines_ma_primary_00f8d9_idx'), models.Index(fields=['next_maintenance_date'], name='machines_ma_next_ma_81259f_idx')],
            },
        ),
    ]
