# Generated by Django 5.2.5 on 2025-08-21 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the setting', primary_key=True, serialize=False)),
                ('key', models.CharField(help_text="Unique setting key (e.g., 'maintenance_interval_days')", max_length=255, unique=True)),
                ('value', models.TextField(help_text='Setting value (can store numbers, text, JSON as string)')),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the setting was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the setting was last updated')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='settingsapp_key_e0d69b_idx'), models.Index(fields=['updated_at'], name='settingsapp_updated_01b934_idx')],
            },
        ),
    ]
