# Generated by Django 5.2.5 on 2025-08-20 19:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the batch workflow', primary_key=True, serialize=False)),
                ('batch_code', models.CharField(help_text='Unique identifier for the textile batch', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the batch workflow', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the batch workflow', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Date when the batch workflow started', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Expected or actual end date of the workflow', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the batch workflow was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the batch workflow was last updated')),
                ('supervisor', models.ForeignKey(help_text='Supervisor responsible for this batch', limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Workflow',
                'verbose_name_plural': 'Batch Workflows',
                'db_table': 'workflow_batch_workflow',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch_code'], name='workflow_ba_batch_c_7da184_idx'), models.Index(fields=['status'], name='workflow_ba_status_cbd3fe_idx'), models.Index(fields=['supervisor'], name='workflow_ba_supervi_4fe6d8_idx'), models.Index(fields=['created_at'], name='workflow_ba_created_5ac5ec_idx'), models.Index(fields=['end_date'], name='workflow_ba_end_dat_b63f63_idx')],
            },
        ),
    ]
