# Generated by Django 5.2.5 on 2025-08-20 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchworkflow',
            name='supervisor',
            field=models.ForeignKey(help_text='Supervisor responsible for this batch', limit_choices_to={'role__in': ['supervisor', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_batches', to=settings.AUTH_USER_MODEL),
        ),
    ]
