# Generated by Django 5.2.5 on 2025-08-20 17:59

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('inspector', 'Quality Inspector'), ('analyst', 'Data Analyst')], default='technician', help_text='User role determines system permissions', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending Activation')], default='pending', help_text='Account status', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Mali phone number format: +223XXXXXXXX', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be Mali format: +223XXXXXXXX', regex='^\\+?223\\d{8}$')])),
                ('employee_id', models.CharField(blank=True, help_text='Format: AB1234 (2 letters + 4-6 digits)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must be format: AB1234 (2 letters + 4-6 digits)', regex='^[A-Z]{2}\\d{4,6}$')])),
                ('department', models.CharField(blank=True, help_text='Department within CMDT', max_length=100)),
                ('site_location', models.CharField(blank=True, help_text='CMDT site/factory location', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True, help_text='Short bio or description', max_length=500)),
                ('login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('supervisor', models.ForeignKey(blank=True, help_text='Direct supervisor', limit_choices_to={'role__in': ['admin', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users_user',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Secure token for password reset', max_length=64, unique=True)),
                ('email', models.EmailField(help_text='Email where reset link was sent', max_length=254)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this token has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration time')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the token was used', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the reset request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the reset request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'users_passwordresettoken',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name (e.g., "Site Manager", "Quality Lead")', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of role responsibilities')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can create, edit, and deactivate users')),
                ('can_manage_machines', models.BooleanField(default=False, help_text='Can add, edit, and configure machines')),
                ('can_manage_workflow', models.BooleanField(default=False, help_text='Can create and manage production workflows')),
                ('can_view_analytics', models.BooleanField(default=False, help_text='Can access analytics and performance reports')),
                ('can_export_reports', models.BooleanField(default=False, help_text='Can export reports to PDF/Excel')),
                ('can_manage_quality', models.BooleanField(default=False, help_text='Can perform quality inspections and manage QC')),
                ('can_upload_photos', models.BooleanField(default=False, help_text='Can upload photos for quality control')),
                ('can_manage_maintenance', models.BooleanField(default=False, help_text='Can schedule and manage maintenance tasks')),
                ('can_view_predictions', models.BooleanField(default=False, help_text='Can view predictive maintenance forecasts')),
                ('can_manage_allocation', models.BooleanField(default=False, help_text='Can allocate resources and manage assignments')),
                ('can_manage_notifications', models.BooleanField(default=False, help_text='Can configure system notifications')),
                ('can_manage_settings', models.BooleanField(default=False, help_text='Can modify system settings and configurations')),
                ('restricted_to_sites', models.JSONField(blank=True, default=list, help_text='List of site codes this role is restricted to (empty = all sites)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'users_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='avatars/')),
                ('birth_date', models.DateField(blank=True, help_text='Date of birth', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender identity', max_length=10)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15)),
                ('hire_date', models.DateField(blank=True, help_text='Date hired at CMDT', null=True)),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Years of experience in textile manufacturing', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('education_level', models.CharField(blank=True, choices=[('primary', 'Primary Education'), ('secondary', 'Secondary Education'), ('technical', 'Technical/Vocational'), ('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('phd', 'PhD')], help_text='Highest education level', max_length=50)),
                ('certifications', models.TextField(blank=True, help_text='Professional certifications (one per line)')),
                ('language_preference', models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('bm', 'Bambara')], default='fr', help_text='Preferred system language', max_length=10)),
                ('timezone', models.CharField(default='Africa/Bamako', help_text='User timezone', max_length=50)),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('total_logins', models.PositiveIntegerField(default=0, help_text='Total number of system logins')),
                ('total_reports_generated', models.PositiveIntegerField(default=0, help_text='Total reports generated by user')),
                ('total_quality_inspections', models.PositiveIntegerField(default=0, help_text='Total quality inspections performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'users_userprofile',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(blank=True, help_text='Site code if role is site-specific', max_length=10)),
                ('valid_from', models.DateTimeField(auto_now_add=True, help_text='When this role assignment becomes valid')),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this role assignment expires (null = permanent)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this role assignment is currently active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this role assignment')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'db_table': 'users_userrole',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='users_user_status_07d06d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_id'], name='users_user_employe_e638d5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_user_created_cf865c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_activity'], name='users_user_last_ac_1898c4_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token'], name='users_passw_token_b56ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['user', 'is_used'], name='users_passw_user_id_5ee9a9_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['expires_at'], name='users_passw_expires_853bc2_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='users_userr_user_id_6be9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='users_userr_role_id_fcacec_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['site_code'], name='users_userr_site_co_b460ae_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['valid_until'], name='users_userr_valid_u_6da110_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'site_code')},
        ),
    ]
